### ISSUE TITLE
Error in multi-gpu distributed training code that works with single gpu

### ISSUE THREAD

**Issue by naruarjun** [parallel-domain/pd-sdk#289] opened 2023-04-23 22:55 UTC
Hello,

I am getting this error when I run a distributed training code:
```
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x7f522c3c5dc0>: it's not the same object as paralleldomain.decoding.dgp.decoder._DatasetDecoderMixin._decode_dataset_dto
```

I am not really sure what is causing this. So any insight on anything in the API that could be causing this will be appreciated.

**Comment by phillip-thomas-pd** [comment] 2023-04-25 09:10
Hey, 
thanks for your Issue! If i assume correctly you are moving PD-SDK objects (Dataset, Scene, Frame or SensorFrame) through your data pipeline? If so the problem is that we have use lru_cache slightly different because of the problem mentioned here (https://rednafi.github.io/reflections/dont-wrap-instance-methods-with-functoolslru_cache-decorator-in-python.html). The problem is that because of that our Decoders are no longer Picklable. Other decoders like the NuScenesDecoder are also not pickleable. So in general we dont ensure that that is given.

The solution we use internally for training with PD-SDK objects is a Pipeline item that just refers to the scene, name, frame id, sensor name etc. Since those are all just strings they can be pickled and therefor be passed between processes in a multi gpu pipeline. And those are the only thing you need to know withing PD-SDK to load a certain Frame or SensorFrame. So you could just use a class like the one below to pass PD-SDK references through your pipeline:


```python
from copy import deepcopy
from dataclasses import dataclass, field
from typing import Any, Dict, Optional, Union

from paralleldomain import Dataset
from paralleldomain.decoding.helper import decode_dataset
from paralleldomain.model.frame import Frame
from paralleldomain.model.sensor import (
    CameraSensor,
    CameraSensorFrame,
    LidarSensor,
    LidarSensorFrame,
    Sensor,
    SensorFrame,
)
from paralleldomain.model.unordered_scene import UnorderedScene
from paralleldomain.utilities.any_path import AnyPath

@dataclass
class PipelineItem:
    sensor_name: Optional[str]
    frame_id: Optional[str]
    scene_name: Optional[str]
    dataset_path: Union[str, AnyPath]
    dataset_format: str
    decoder_kwargs: Dict[str, Any]
    custom_data: Dict[str, Any] = field(default_factory=dict)

    @property
    def dataset(self) -> Dataset:
        return decode_dataset(dataset_format=self.dataset_format, dataset_path=self.dataset_path, **self.decoder_kwargs)

    @property
    def scene(self) -> Optional[UnorderedScene]:
        if self.scene_name is not None:
            return self.dataset.get_unordered_scene(scene_name=self.scene_name)
        return None

    @property
    def sensor(self) -> Optional[Sensor]:
        if self.sensor_name is not None:
            return self.scene.get_sensor(sensor_name=self.sensor_name)
        return None

    @property
    def frame(self) -> Optional[Frame]:
        if self.frame_id is not None:
            return self.scene.get_frame(frame_id=self.frame_id)
        return None

    @property
    def sensor_frame(self) -> Optional[SensorFrame]:
        if self.frame_id is not None and self.sensor_name is not None:
            return self.sensor.get_frame(frame_id=self.frame_id)
        return None

    @property
    def camera_frame(self) -> Optional[CameraSensorFrame]:
        if self.sensor is not None and isinstance(self.sensor, CameraSensor):
            return self.sensor.get_frame(frame_id=self.frame_id)
        return None

    @property
    def lidar_frame(self) -> Optional[LidarSensorFrame]:
        if self.sensor is not None and isinstance(self.sensor, LidarSensor):
            return self.sensor.get_frame(frame_id=self.frame_id)
        return None

    def clone(self, clone_custom_data: bool = True) -> "PipelineItem":
        custom_data = dict()
        if clone_custom_data:
            custom_data = deepcopy(self.custom_data)
        return PipelineItem(
            custom_data=custom_data,
            dataset_format=self.dataset_format,
            dataset_path=self.dataset_path,
            scene_name=self.scene_name,
            frame_id=self.frame_id,
            sensor_name=self.sensor_name,
            decoder_kwargs=self.decoder_kwargs,
        )


```
I hope that helps! Let me know if not.

**Comment by pd-nisse** [comment] 2023-05-18 21:58
@naruarjun I'm closing this issue for now. If you are still encountering issue or have questions, please feel free to reach out again.

**Closed by pd-nisse** 2023-05-18 21:58 UTC
